/** UI 文案（UTF-8 中文） */
export const S = {
  defaultTournamentName: '我的赛事',
  unnamedPlayer: '未命名',

  // Player panel
  tournamentNameTitle: '为本场赛事设置名称，将显示在页面顶部',
  tournamentName: '赛事名称',
  tournamentNamePlaceholder: '例如：周末俱乐部循环赛',
  tournamentNameInputTitle:
    '输入赛事名称，失焦后自动去除首尾空格；留空则恢复为「我的赛事」',
  addPlayerTitle: '添加参加本次比赛的球员',
  addPlayer: '添加球员',
  addPlayerHint: '输入姓名并选择性别与等级（Lv1–Lv9）后添加',
  addPlayerHintTitle: '球员数据保存在浏览器本地，关闭页面后仍会保留',
  gender: '性别',
  genderTitle: '选择球员性别',
  genderMale: '♂',
  genderFemale: '♀',
  genderMaleOption: '男',
  genderFemaleOption: '女',
  genderUnspecified: '·',
  genderMaleTitle: '男性球员',
  genderFemaleTitle: '女性球员',
  genderUnspecifiedTitle: '性别未指定',
  genderShort: (g: 'male' | 'female' | 'unspecified') =>
    g === 'male' ? '♂' : g === 'female' ? '♀' : '·',
  level: '等级',
  levelTitle: '选择技术等级 Lv1（初学）至 Lv9（职业）',
  levelLabel: (lv: number) => `Lv${lv}`,
  levelOptionTitle: (lv: number) => `等级 Lv${lv}`,
  editGenderTitle: (i: number) => `编辑第 ${i} 位球员性别`,
  editLevelTitle: (i: number) => `编辑第 ${i} 位球员等级`,
  playerNamePlaceholder: '球员姓名',
  playerNameInputTitle: '输入新球员姓名，按 Enter 或点击「添加」按钮',
  addButton: '添加',
  addButtonTitle: '将上方输入的姓名加入球员列表',
  playerListTitle: '可点击姓名直接修改，至少需 2 人才能生成对阵',
  playerList: (n: number) => `球员列表（${n}）`,
  emptyPlayersTitle: '请先在上方添加球员',
  emptyPlayers: '还没有球员，先添加至少 2 人',
  editPlayerTitle: (i: number) =>
    `编辑第 ${i} 位球员姓名，失焦时自动去除首尾空格`,
  delete: '删除',
  deletePlayer: (name: string) => `从列表中移除 ${name}`,
  deleteAria: (name: string) => `删除 ${name}`,

  // Setup panel
  modeTitle: '选择单打或双打，将影响对阵生成方式',
  mode: '比赛模式',
  singles: '单打',
  singlesTitle: '单打：每位球员与其他所有球员各打一场循环赛',
  doubles: '双打',
  doublesTitle: '双打：球员两两组队后，各队伍之间循环对阵',
  teamGroupTitle: '为每队选择两名球员，同一人不能重复出现在多队',
  teamGroup: '双打分组',
  teamGroupHint: '可调整每队两名球员，或一键按添加顺序自动配对',
  teamGroupHintTitle: '可手动调整下拉框中的配对，或按添加顺序一键配对',
  teamN: (n: number) => `第 ${n} 队`,
  teamNTitle: (n: number) => `第 ${n} 组双打队伍`,
  autoPair: '按顺序自动配对',
  autoPairTitle:
    '按球员列表顺序两两配对：第 1、2 人为一队，第 3、4 人为一队，以此类推',
  scheduleFormatTitle: '选择循环赛、小组赛或淘汰赛对阵方式',
  scheduleFormat: '对阵方式',
  roundRobin: '循环赛',
  roundRobinTitle: '全员互打；每次生成随机排序，并避免连续上场',
  groupStage: '小组赛',
  groupStageTitle: '随机分组后组内循环，再交叉淘汰赛决冠亚军（无季军赛）',
  knockoutOnly: '淘汰赛',
  knockoutOnlyTitle:
    '单败淘汰：随机排签；人数非 2 的幂次时随机轮空，仅决冠亚军',
  knockoutOnlyHint:
    '单败淘汰，仅决赛决冠亚军，无季军赛；人数非 2 的幂次时随机轮空补齐签表',
  roundRobinHint: '点击生成时随机打乱顺序，并尽量避免同一球员连场',
  groupStageHint:
    '随机分组后组内循环排名；各组同名次交叉淘汰，组数非 2/4/8/16 时随机轮空补齐',
  groupCount: '小组数',
  groupCountTitle: '将当前人数随机分入各组（组内至少 2 人）；淘汰阶段自动轮空补齐签位',
  groupAssignment: '分组结果',
  groupLabel: (n: number) => `第 ${n} 组`,
  groupMembers: (n: number) => `本组 ${n} 人`,
  groupMemberSeparator: ' · ',
  scheduleTitle: '根据当前设置生成对阵表',
  schedule: '生成对阵表',
  statPlayers: '球员',
  statPlayersTitle: '当前已添加的球员总数',
  statTeams: '队伍',
  statTeamsTitle: '双打模式下的队伍数量',
  statMatches: '预计场次',
  statMatchesTitle: '含小组赛与淘汰赛总场次',
  generate: '生成对阵',
  generateDisabledTitle: '至少需要 2 名球员才能生成对阵',
  generateTitle: '随机分组并生成小组循环赛与淘汰赛对阵',
  viewMatches: '查看已有对阵',
  viewMatchesTitle: '查看已生成的对阵与已录入的比分',
  regenWarning: '重新生成将覆盖当前对阵与比分',
  regenWarningTitle: '重新生成会清空当前所有对阵记录与比分',
  fullSchedule: '全部对战表',
  fullScheduleTitle: '小组赛与淘汰赛场次一览',
  scheduleTotal: '共',
  scheduleTotalTitle: '总场次数',
  scheduleGroups: '小组',
  scheduleGroupsTitle: '小组赛组数',
  scheduleKnockout: '淘汰赛',
  scheduleScored: '已录分',
  scheduleMatchesUnit: '场',
  matrix: '对阵矩阵',
  matrixTitle: '行列交叉查看任意两方的对战与比分（仅循环赛）',
  matrixHint: '横轴为甲方、纵轴为乙方；数字为已录入比分，# 为场次序号',
  matrixCellTitle: (a: string, b: string, order: number, score: string) =>
    score ? `${a} vs ${b}：${score}` : `${a} vs ${b}，第 ${order} 场`,
  matrixPendingOrder: (order: number) => `#${order}`,
  matchNoTitle: (n: number) => `第 ${n} 场`,
  matchPendingShort: '待赛',
  goScore: '去录入比分',
  goScoreTitle: '跳转到比分页录入各场比分',

  // Knockout
  sectionKnockout: '淘汰赛',
  knockoutStage: '淘汰赛',
  knockoutQuarter: '1/4 决赛',
  knockoutSemi: '半决赛',
  knockoutThirdLegacy: '季军赛（已停用）',
  knockoutFinal: '决赛',
  knockoutSlotGroupRank: (group: number, rank: number) =>
    `第 ${group} 组第 ${rank} 名`,
  knockoutSlotWinner: '上一场胜者',
  knockoutSlotLoser: '上一场负者',
  knockoutWaitGroup: '请先完成全部小组赛',
  knockoutWaitPrior: '请先完成前置淘汰赛',
  knockoutLocked: '对阵尚未确定，暂不可录入',
  knockoutBracketHint:
    '小组赛结束后交叉淘汰决冠亚军（无季军赛）；组数非 2 的幂次时随机轮空补齐',
  knockoutBye: '轮空',
  knockoutByeShort: '轮空晋级',
  knockoutCross: '交叉赛',
  knockoutCrossRank: (rank: number) => `小组第 ${rank} 名交叉`,
  knockoutRankMatch: (rank: number, stage: string) =>
    `小组第 ${rank} 名 · ${stage}`,

  // Match panel
  filterByGroup: '按阶段筛选',
  filterAllGroups: '全部',
  filterAllGroupsTitle: '显示所有比赛',
  filterGroupTitle: (g: number, done: number, total: number) =>
    `第 ${g} 组：已录 ${done}/${total} 场`,
  filterKnockoutTitle: '仅显示淘汰赛',
  filterByStatus: '按状态筛选',
  noMatchesInFilter: '当前筛选条件下暂无比赛',
  sectionAllMatches: '全部场次',
  sectionProgress: (done: number, total: number) =>
    `已录入 ${done}/${total} 场`,
  filterAll: '全部',
  filterPending: '未赛',
  filterDone: '已赛',
  noMatchesTitle: '请先在「对阵」页生成对阵表',
  noMatches: '还没有对阵表',
  goSchedule: '去生成对阵',
  goScheduleTitle: '前往对阵页设置模式并生成对阵',
  scoreEntryTitle: '录入每场对阵的双方得分，用于计算排名',
  scoreEntry: '比分录入',
  doneStat: '已完成',
  doneStatTitle: '已录入比分的场次 / 总场次',
  scoreHint:
    '大分=盘/局数，小分=抢七等（可空，默认 0）。示例：输入 7、7 和 6、5 → 7(7):6(5)，填好自动保存',
  scoreHintTitle: '比分录入规则：大分小分分别填写，小分可留空',
  clearScore: '清除',
  clearScoreTitle: '清除本场比分，恢复为未赛状态',

  // Ranking panel
  noRankTitle: '需先有对阵并录入至少一场比赛',
  noRank: '录入比分后将自动生成排名',
  goSetup: '去设置赛事',
  goSetupTitle: '前往对阵页生成对阵表',
  rankingTitle: '根据已录入比分自动计算的排名',
  ranking: '比赛排名',
  rankingGroupStage: '小组排名',
  rankingGroupStageHint:
    '统计含已录入的小组赛与淘汰赛全部场次（轮空按比分计入）；表内仅显示名次与净胜局。排序：胜场 → 净胜局 → 总得分 → 相互战绩',
  rankingOverall: '循环赛总排名',
  groupStandingsTitle: (g: number) => `第 ${g} 组积分榜`,
  groupStandingsAll: '综合排名',
  combinedRankHintKnockout:
    '统计含已录入的淘汰赛全部场次（轮空按比分计入）；表内仅显示名次与净胜局。排序：胜场 → 净胜局 → 总得分 → 相互战绩',
  championBanner: (name: string) => `冠军：${name}`,
  runnerUpNote: '决赛负者为亚军',
  finishedMatches: (done: number, total: number) =>
    `已结束 ${done} / ${total} 场`,
  modeStat: '模式',
  rankRule: '排序规则：胜场 → 净胜局 → 总得分 → 相互战绩（表内仅显示名次与净胜局）',
  rankRuleTitle:
    '同分情况下依次比较：胜场数、净胜局、总得分、相互间战绩',
  noData: '暂无数据',
  noDataTitle: '请先在比分页录入比赛结果',
  tableTitle: '积分榜',
  colRank: '#',
  colPlayer: '球员',
  colTeam: '队伍',
  colGroup: '小组',
  colPlayed: '场次',
  colWin: '胜',
  colLoss: '负',
  colRecord: '胜负',
  colDiff: '净胜局',
  standingRecord: (wins: number, losses: number) => `${wins}胜${losses}负`,
  standingRowTitle: (rank: number, diff: number) =>
    `第 ${rank} 名，净胜局 ${diff > 0 ? '+' : ''}${diff}`,
  champion: '冠军',
  rankN: (n: number) => `第 ${n} 名`,
  podiumTitle: '颁奖台',
  podiumGold: '冠军',
  podiumSilver: '亚军',
  podiumPending: '待定',
  podiumHint: '小组赛+淘汰赛：决赛结束后显示冠亚军',
  podiumHintRoundRobin: '录入比分后按积分榜冠亚军展示',

  // Errors
  errMinPlayers: '至少需要 2 名球员',
  errDoublesEven: '双打需要偶数名球员',
  errMinTeams: '至少需要 2 组双打队伍',
  errTeamCoverage: '每位球员必须且只能加入一队',
  errMinGroups: '小组数至少为 2',
  errGroupsTooMany: '小组数不能大于参赛人数',
  errGroupsTooSmall: '人数过少，无法分成至少 2 人的多个小组',
  errKnockoutTooMany: '淘汰赛签表最多支持 32 个签位（请减少人数或组数）',
  rankingKnockout: '淘汰赛签表',
  podiumHintKnockout: '决赛结束后显示冠亚军',

  // App
  appTitle: '网球赛事计分工具',
  localSave: '本地保存 · 可安装到手机桌面',
  localSaveTitle: '数据保存在浏览器本地；支持安装为 PWA 应用',
  dataMgmt: '数据管理',
  dataMgmtTitle: '管理本地赛事数据',
  dataHint: '所有数据保存在浏览器本地，清除缓存会丢失',
  dataHintTitle: '数据存储在 localStorage，清除浏览器数据会丢失',
  newTournament: '新建赛事',
  newTournamentTitle: '清空当前球员、对阵与比分，开始全新赛事',
  confirmReset: '确定新建赛事？当前球员、对阵与比分将被清空。',
  tabPlayers: '球员',
  tabPlayersTitle: '添加与管理球员',
  tabSetup: '对阵',
  tabSetupTitle: '选择模式并生成对阵表',
  tabMatches: '比分',
  tabMatchesTitle: '录入各场比分',
  tabRankings: '排名',
  tabRankingsTitle: '查看积分榜与冠军',

  unknown: '未知',
} as const;
